import Image from "next/image";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sherpa Recorder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Image
          className="pointer-events-none object-cover mix-blend-darken"
          src="/beams-basic.png"
          alt="Beams background"
          fill={true}
          priority
        />

        {children}

        <Image
          className="-z-30 object-cover opacity-50 mix-blend-darken"
          src="/beams-basic2.jpg"
          alt="Beams background"
          fill={true}
          priority
        />
      </body>
    </html>
  );
}
